### ISSUE TITLE
Troubles regarding the six-word essays

### ISSUE THREAD

**Issue by PabloMenendez1** [PabloMenendez1/hello-world#3]
As I have two classes with you, I have to do similar types of work in both of them. This includes writing six-word essays that are meant to reflect my opinion of the class, whether it relates to the class in its entirety or just one specific part of it that drew my interest. However, I get confused when I comes to which document I put my thoughts on, given there is little difference between the two before I actually open the doc. Is it okay if I can throw in my own little edits as to not get as confused?

**Comment by Adam-Klemann** [comment]
Sure. No problem. Please edit the documents as you see fit in the headers.
I would like the actual six word essays themselves to remain.

-Adam
